--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/sky-min/MoenyAPI
build-by-default: true
branches:
- master
projects:
  MoneyAPI:
    path: MoneyAPI/
    libs:
      - src: 	skymin\json/JsonData
        version: ^SKY
      - src: skymin/traits/pmmp-SimpleTrait
        version: ^SKY
...
